#!/bin/sh php
<?php

declare(strict_types=1);

use App\Shared\Database\Database;
use Dotenv\Dotenv;
use League\Container\Container;
use Symfony\Component\Console\Application;

if (!defined('CONSOLE_APP')) {
    define('CONSOLE_APP', true);
}

/**
 * @var Container $container
 */
require 'app/bootstrap.php';

$db = $container->get(Database::class);
try {
    $consoleApp = $container->get(Application::class);

    $consoleApp->run();
    /**
     * @var Database $db
     */
    $db->commit();
}
catch (Throwable $e) {
    $db = $container->get(Database::class);
    $db->rollback();
    /** @noinspection PhpUnhandledExceptionInspection */
    throw $e;
}
